version: '3'
services:
  # Serviço RabbitMQ
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"  # Porta para acessar o gerenciamento do RabbitMQ no navegador
      - "5672:5672"    # Porta para comunicação do RabbitMQ com outros containers
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  # Serviço Python para produtor
  produtor:
    build: ./src/s1
    command: python3 produtor.py
    volumes:
      - ./src/s1:/app
    depends_on:
      - rabbitmq

  # Serviço Python para consumidor
  consumidor:
    build: ./src/s2
    command: python3 consumidor.py
    volumes:
      - ./src/s2:/app
    depends_on:
      - rabbitmq
